## Install numpy:
```bash
pip install numpy
```
---

## Why is numpy so fast?

Because of **vectorization**. 

> What is Vectorization ?

Vectorization is used to speed up the Python code without using loop. Using such a function can help in minimizing the running time of code efficiently. Various operations are being performed over vector such as dot product of vectors which is also known as scalar product as it produces single output, outer products which results in square matrix of dimension equal to length X length of the vectors, Element wise multiplication which products the element of same indexes and dimension of the matrix remain unchanged.

---

## Import numpy and check its version

In [1]:
import numpy as np
np.__version__

'1.25.2'

---

## Numpy special constants

In [2]:
## numpy special constants

print("pi in numpy: ", np.pi)
print("e in numpy: ", np.e)
print("e raised to 2: ", np.exp(2))
print("natural log of 2: ", np.log(2)) # natural log
print("log of 2 to base 10: ", np.log10(2))
print("log of 2 to base 2: ", np.log2(2))

print("=====================================")
print("infinity: ", np.inf)
print("type of infinity: ", type(np.Infinity))

pi in numpy:  3.141592653589793
e in numpy:  2.718281828459045
e raised to 2:  7.38905609893065
natural log of 2:  0.6931471805599453
log of 2 to base 10:  0.3010299956639812
log of 2 to base 2:  1.0
infinity:  inf
type of infinity:  <class 'float'>


---

## Creating numpy arrays

    - np.array() -> create an array from a list or tuple
    - np.zeros() -> create an array of zeros
    - np.ones() -> create an array of ones
    - np.full() -> create an array of a specific value
    - np.empty() -> create an array of empty values
    - np.arange() -> create an array of values from start to end
    - np.linspace() -> create an array of values from start to end with a specific number of elements

In [3]:
# np.array() function

myList = [1, 2, 3, 4, 5]
myArray = np.array(myList)
print(f"myArray: {myArray}; type: {type(myArray)}")

myTup = (1, 2, 3, 4, 5)
myArray = np.array(myTup)
print(f"myArray: {myArray}; type: {type(myArray)}")

my2DList = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
myArray = np.array(my2DList)
print(f"myArray: {myArray}; type: {type(myArray)}")

print("------------------------------------------------------------")
print("------------------------------------------------------------")

# np.zeros() function
# pass in a tuple of the dimensions of the array and the data type (default is float)
myZeros = np.zeros((3, 4), dtype=int)
print(f"myZeros: {myZeros}; type: {type(myZeros)}")

print("------------------------------------------------------------")
print("------------------------------------------------------------")

# np.ones() function

myOnes = np.ones((3, 2))
print(f"myOnes: {myOnes}; type: {type(myOnes)}")

print("------------------------------------------------------------")
print("------------------------------------------------------------")

# np.full() function
# returns a new array of given shape and type, filled with fill_value
# fill_value is a scalar value

myFull = np.full((3, 4), 10)
print(f"myFull: {myFull}; type: {type(myFull)}")

print("------------------------------------------------------------")
print("------------------------------------------------------------")

# np.empty() function
# returns an array of random values.
# The function empty creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

myEmpty = np.empty((2, 4), dtype=np.int64)
print(f"myEmpty: {myEmpty}; type: {type(myEmpty)}")

print("------------------------------------------------------------")
print("------------------------------------------------------------")

# np.arange() function
# returns evenly spaced values within a given interval
# start (default is 0), stop (excluded), step (default is 1)

myRange1 = np.arange(0, 10, 2)
print(f"myRange1: {myRange1}; type: {type(myRange1)}")

myRange2 = np.arange(0, 10) # start, stop, step (default is 1)
print(f"myRange2: {myRange2}; type: {type(myRange2)}")

myRange3 = np.arange(10) # start (default is 0), stop, step (default is 1)
print(f"myRange3: {myRange3}; type: {type(myRange3)}")

print("------------------------------------------------------------")
print("------------------------------------------------------------")

# np.linspace() function
# returns evenly spaced numbers over a specified interval
# start, stop, num (default is 50), endpoint (default is True), retstep {return step (spacing between adjacent elements)} (default is False), dtype (default is None)

myLinspace1 = np.linspace(0, 10, 5)
print(f"myLinspace1: {myLinspace1}; type: {type(myLinspace1)}")

myLinspace2 = np.linspace(0, 10, 5, endpoint=False)
print(f"myLinspace2: {myLinspace2}; type: {type(myLinspace2)}")

myLinspace3 = np.linspace(0, 10, 5, retstep=True)
print(f"myLinspace3: {myLinspace3}; type: {type(myLinspace3)}")

myLinspace4 = np.linspace(0, 10, 5, dtype=int)
print(f"myLinspace4: {myLinspace4}; type: {type(myLinspace4)}")

myLinspace5 = np.linspace(0, 10) # default num is 50
print(f"myLinspace5: {len(myLinspace5)}; type: {type(myLinspace5)}")



myArray: [1 2 3 4 5]; type: <class 'numpy.ndarray'>
myArray: [1 2 3 4 5]; type: <class 'numpy.ndarray'>
myArray: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]; type: <class 'numpy.ndarray'>
------------------------------------------------------------
------------------------------------------------------------
myZeros: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]; type: <class 'numpy.ndarray'>
------------------------------------------------------------
------------------------------------------------------------
myOnes: [[1. 1.]
 [1. 1.]
 [1. 1.]]; type: <class 'numpy.ndarray'>
------------------------------------------------------------
------------------------------------------------------------
myFull: [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]; type: <class 'numpy.ndarray'>
------------------------------------------------------------
------------------------------------------------------------
myEmpty: [[94826988281939              0              0              0]
 [             0              0  

---

## Generating array with random numbers

- The use of random number generation is an important part of the configuration and evaluation of many numerical and machine learning algorithms.

- Whether you `need to randomly initialize weights in an artificial neural network`, split data into random sets, or randomly shuffle your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential.



In [4]:
np.random.seed(1234)
array = np.random.randint(0, 10, (5, 5))
print(array)
print("=====================================")
newArr = np.random.random((5, 5))
print(newArr)

[[3 6 5 4 8]
 [9 1 7 9 6]
 [8 0 5 0 9]
 [6 2 0 5 2]
 [6 3 7 0 9]]
[[0.07538124 0.36882401 0.9331401  0.65137814 0.39720258]
 [0.78873014 0.31683612 0.56809865 0.86912739 0.43617342]
 [0.80214764 0.14376682 0.70426097 0.70458131 0.21879211]
 [0.92486763 0.44214076 0.90931596 0.05980922 0.18428708]
 [0.04735528 0.67488094 0.59462478 0.53331016 0.04332406]]


---

## Sort a numpy array

In [5]:
# np.sort() returns a sorted copy of an array
# by default it sorts along the last axis (axis = -1)
myArr = np.array([[4,3,2],[43,21,1]])

myArr = np.sort(myArr)
print(myArr)

print("------------------")
# we can also sort along a specific axis
myArr = np.sort(myArr, axis = 0)
print(myArr)

[[ 2  3  4]
 [ 1 21 43]]
------------------
[[ 1  3  4]
 [ 2 21 43]]


---

# Concatenate two arrays

In [6]:
# The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

a = np.arange(15).reshape(3, 5)

b = np.arange(17, 32).reshape(3, 5)

print(a)
print(b)

print("--------------------")
print(np.concatenate((a, b))) # axis=0 (default)
print("--------------------")

print(np.concatenate((a, b), axis=0))
print("--------------------")

b = np.arange(17, 44).reshape(3, 9)

print(np.concatenate((a, b), axis=1))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]]
--------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]]
--------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]]
--------------------
[[ 0  1  2  3  4 17 18 19 20 21 22 23 24 25]
 [ 5  6  7  8  9 26 27 28 29 30 31 32 33 34]
 [10 11 12 13 14 35 36 37 38 39 40 41 42 43]]


---

## know the shape and size of array

- `ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

- `ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

- `ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. 

In [7]:
b = np.arange(17, 44).reshape(3, 9)

print(f"dimensions: {b.ndim}")
print(f"shape: {b.shape}")
print(f"size: {b.size}")

dimensions: 2
shape: (3, 9)
size: 27


---

## Reshape the array

In [8]:
a = np.arange(15)
print(a)
print("--------------------")

# now, let's reshape it
b = a.reshape(3, 5)
print(b)
print("--------------------")

# let's reshape it again with (-1)
c = a.reshape(5, -1) # -1 means "whatever is needed"
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
--------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


---

## Indexing & Slicing

In [9]:
a = np.arange(15).reshape(3, 5)

print(a)
print("--------------------")

# to access first row
print(a[0])
print("--------------------")

# to access first column
print(a[:, 0])
print("--------------------")

# to access i'th row j'th column
print(a[1, 2]) # 2nd row, 3rd column
print("--------------------")

# using negative index
print(a[-2:, -3:]) # last row, last column
print("--------------------")


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------
[0 1 2 3 4]
--------------------
[ 0  5 10]
--------------------
7
--------------------
[[ 7  8  9]
 [12 13 14]]
--------------------


---

## selecting a subset of rows and columns based on a condition

In [10]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [3, 10, 1, 12]])

print(a<5)

print("------------------")

print(a[a<5])

[[ True  True  True  True]
 [False False False False]
 [ True False  True False]]
------------------
[1 2 3 4 3 1]


In [11]:
## selecting elements which are even (divisible by 2)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr % 2 == 0)
print("--------------------")
print(arr[arr % 2 == 0])

[[False  True False]
 [ True False  True]
 [False  True False]]
--------------------
[2 4 6 8]


In [12]:
# selecting elements which are either less than 4 or greater than 7
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

mask = (arr < 4) | (arr > 7)
print(mask)
print("------------------")
print(arr[mask])

[[ True  True  True]
 [False False False]
 [False  True  True]]
------------------
[1 2 3 8 9]


---

## `np.nonzero` - find indices of non-zero elements

- for 1D array, returns a tuple of indices for non-zero elements

- for 2D array, returns a tuple of arrays of row and column indices for non-zero elements.
The first array contains row indices, the second array contains column indices.
`arr[row_indices[i], col_indices[i]] will be non-zero for i in range(len(row_indices))`.

In [13]:
## for 1D array

print("> For 1D array\n")
arr = np.arange(10)
print(arr)

print("------------------")

nonZeroIndices = np.nonzero(arr%2==0)
print(nonZeroIndices)

print("------------------")

print(arr[nonZeroIndices])

print("------------------")
print("------------------")

## for 2D array
print("\n> For 2D array\n")

arr = arr.reshape(2,5)
print(arr)

print("------------------")

nonZeroIndices = np.nonzero(arr%2==0)
print(nonZeroIndices)

print("------------------")

print(arr[nonZeroIndices])

> For 1D array

[0 1 2 3 4 5 6 7 8 9]
------------------
(array([0, 2, 4, 6, 8]),)
------------------
[0 2 4 6 8]
------------------
------------------

> For 2D array

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------
(array([0, 0, 0, 1, 1]), array([0, 2, 4, 1, 3]))
------------------
[0 2 4 6 8]


---

## `np.hstack`, `np.vstack`, `np.hsplit`

- `np.hstack` : horizontally stack

- `np.vstack` : vertically stack

- `np.hsplit` : horizontally split

In [14]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

print("np.hstack([a1, a2]) =\n", np.hstack([a1, a2]))
print("------------------")

print("np.vstack([a1, a2]) =\n", np.vstack([a1, a2]))
print("------------------")

x = np.arange(1, 25).reshape(2, 12)
print("x =\n", x)
print("------------------")

print("np.hsplit(x, 3) =\n", np.hsplit(x, 3)) # Split into 3 equal-shaped arrays

np.hstack([a1, a2]) =
 [[1 1 3 3]
 [2 2 4 4]]
------------------
np.vstack([a1, a2]) =
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]
------------------
x =
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
------------------
np.hsplit(x, 3) =
 [array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


---

## Shallow Copy (View) and Deep Copy

🛑 If you wish to copy a slice of a bigger array, first you should slice it and then copy it. Doing it the other way around, will take more time and memory. (Creating deep copy is expensive)

In [15]:
# No copy at all
a = np.arange(12).reshape(3, 4)
b = a
print("is a & b same? ",b is a) # b is just a reference of a. Any change in b will affect a

# in python, we have an `id` function to check the memory address of a variable. It's different for each unique object
print("id of a: ",id(a))
print("id of b: ",id(b))

is a & b same?  True
id of a:  139935537890480
id of b:  139935537890480


In [16]:
# shallow copy (view)
# - Different array objects can share the same data. 
# The view method creates a new array object that looks at the **same data**.

a = np.arange(12).reshape(3, 4)
c = a.view()

print("is a & c same? ",c is a) # False, because they are different objects
print("a & c base is same? ",c.base is a) # True, because they share the same data

# id will be different, because they are different objects
print("id of a: ",id(a))
print("id of c: ",id(c))

# change the shape of c. a's shape will not change
c = c.reshape(2, 6)
print("a.shape: ",a.shape)
print("c.shape: ",c.shape)

# BUT, change the value of c. a's value will change
c[0, 4] = 1234
print("a: ",a)

# slicing an array returns a view of it
s = a[:, 1:3]
print("\n***slicing an array returns a view of it. Different objects, but same data***\n")

is a & c same?  False
a & c base is same?  False
id of a:  139935537891248
id of c:  139935537891344
a.shape:  (3, 4)
c.shape:  (2, 6)
a:  [[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]

***slicing an array returns a view of it. Different objects, but same data***



In [17]:
# deep copy
# The copy method makes a complete copy of the array and its data.

a = np.arange(12).reshape(3, 4)
b = a.copy()  # deep copy

print("is a and b the same object?", a is b) # False, they are different objects, and a and b have different memory addresses and separate data

print("id of a:", id(a))
print("id of b:", id(b)) # different memory addresses

print("a & b base is same? ",b.base is a) # False, b doesn't share anything with a

b[0, 0] = 100
print("a:\n", a)
print("changing b doesn't affect a")


is a and b the same object? False
id of a: 139935537891728
id of b: 139935537891248
a & b base is same?  False
a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
changing b doesn't affect a


---

## Basic numpy array operations

- axis-0: rows
- axis-1: columns

## How to remember: 🍏 🪵
- Suppose, you've a log of wood and you want to cut it into pieces.
- If you `cut it vertically`, it'll be `axis=0`.
- If you `cut it horizontally`, it'll be `axis=1`.


### Trick 😎:
    - If you want to find sum/min/etc along rows, use axis=1
    - If you want to find sum/min/etc along columns, use axis=0

In [18]:
a = np.arange(12).reshape(3, 4)
print("a:", a)
print("=======================================")
print("min of all elements:", a.min())
print("min of each column (axis = 0):", a.min(axis=0))
print("min of each row (axis = 1):", a.min(axis=1))
print("=======================================")
print("max of all elements:", a.max())
print("max of each column:", a.max(axis=0))
print("max of each row:", a.max(axis=1))
print("=======================================")
print("sum of all elements:", a.sum())
print("sum of each column:", a.sum(axis=0))
print("sum of each row:", a.sum(axis=1))
print("=======================================")
print("mean of all elements:", a.mean())
print("mean of each column:", a.mean(axis=0))
print("mean of each row:", a.mean(axis=1))
print("=======================================")
print("standard deviation of all elements:", a.std())
print("standard deviation of each column:", a.std(axis=0))
print("standard deviation of each row:", a.std(axis=1))
print("=======================================")
print("variance of all elements:", a.var())
print("variance of each column:", a.var(axis=0))
print("variance of each row:", a.var(axis=1))
print("=======================================")



a: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
min of all elements: 0
min of each column (axis = 0): [0 1 2 3]
min of each row (axis = 1): [0 4 8]
max of all elements: 11
max of each column: [ 8  9 10 11]
max of each row: [ 3  7 11]
sum of all elements: 66
sum of each column: [12 15 18 21]
sum of each row: [ 6 22 38]
mean of all elements: 5.5
mean of each column: [4. 5. 6. 7.]
mean of each row: [1.5 5.5 9.5]
standard deviation of all elements: 3.452052529534663
standard deviation of each column: [3.26598632 3.26598632 3.26598632 3.26598632]
standard deviation of each row: [1.11803399 1.11803399 1.11803399]
variance of all elements: 11.916666666666666
variance of each column: [10.66666667 10.66666667 10.66666667 10.66666667]
variance of each row: [1.25 1.25 1.25]


---

## Arithmetic operations between 2 NumPy arrays

- If the arrays have the same shape, the operation is done element-wise

- If the arrays do not have the same shape, NumPy will try to broadcast them to the same shape. If they cannot be broadcast, a `ValueError` is raised.

- `To be broadcasted, the size of each dimension must be either the same or one of them is 1.`

In [19]:
a = np.arange(15).reshape(3, 5)
b = np.arange(15,30).reshape(3, 5)
c = 2

# we can perform all the below operations on numpy arrays

# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)
# print(a%b)
# print(a**b)

# =====================

# broadcasting

# print(a+c)
# print(a-c)
# print(a*c)
# print(a/c)
# print(a%c)
# print(a**c)

---

## Matrices

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

print("=====================================")
print("Creating an identity matrix using numpy.eye(no_of_rows)")
print(np.eye(3))
print("=====================================")
print("Creating an array of zeros using numpy.zeros((no_of_rows, no_of_columns))")
print(np.zeros((3, 3)))
print("=====================================")
print("Creating an array of ones using numpy.ones((no_of_rows, no_of_columns))")
print(np.ones((3, 3)))
print("=====================================")
print("Creating an array of random numbers using numpy.random.rand(no_of_rows, no_of_columns)")
print(np.random.rand(3, 3))

[[1 2 3]
 [4 5 6]]
Creating an identity matrix using numpy.eye(no_of_rows)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Creating an array of zeros using numpy.zeros((no_of_rows, no_of_columns))
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Creating an array of ones using numpy.ones((no_of_rows, no_of_columns))
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Creating an array of random numbers using numpy.random.rand(no_of_rows, no_of_columns)
[[0.56143308 0.32966845 0.50296683]
 [0.11189432 0.60719371 0.56594464]
 [0.00676406 0.61744171 0.91212289]]


---

## reversing the array

- use `np.flip` to reverse the array

- For 2D array, it reverses both rows and columns

- We can specify the axis to reverse

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print(reversed_arr)
print("==================")
arr = arr.reshape(2, 4)
print("arr: ",arr)
print("==================")
reversed_arr = np.flip(arr)
print("reversed_arr: ",reversed_arr) 
print("==================")
reversed_arr = np.flip(arr, axis=0)
print("reversed_arr along row: ",reversed_arr)
print("==================")
reversed_arr = np.flip(arr, axis=1)
print("reversed_arr along column: ",reversed_arr)

[8 7 6 5 4 3 2 1]
arr:  [[1 2 3 4]
 [5 6 7 8]]
reversed_arr:  [[8 7 6 5]
 [4 3 2 1]]
reversed_arr along row:  [[5 6 7 8]
 [1 2 3 4]]
reversed_arr along column:  [[4 3 2 1]
 [8 7 6 5]]


---

## Flattening a multi-dimensional array

- `flatten()` returns a copy of the array collapsed into one dimension.
- `ravel()` returns a view of the original array collapsed into one dimension.


In [22]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1) # Flattened array

print("=======================================")

a2 = x.ravel()
a2[0] = 99
print(x)  # Original array
print(a2) # Flattened array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


---

## Transpose of matrix

- we can use both `transpose` and `T` to transpose a matrix


In [23]:
a = np.arange(15).reshape(3, 5)
print(a)
print("=======================")
print(a.T)
print("a transpose shape: ", a.T.shape)
print("=======================")
print(a.transpose())
print("a transpose shape: ", a.transpose().shape)
print("=======================")
print("'a' remains the same. The above operations return a new array and do not modify the original array.")
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
a transpose shape:  (5, 3)
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
a transpose shape:  (5, 3)
'a' remains the same. The above operations return a new array and do not modify the original array.
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


---

## `matrix multiplication` (dot product)

- no of columns in first matrix must be equal to no of rows in second matrix

- `np.dot(a,b)` or `a.dot(b)` or `a @ b`

In [24]:
a = np.arange(15).reshape(3, 5)
b = np.arange(90,105).reshape(5, 3)

print(a)
print(b)
print("====================")
print("dot product of a and b: ")
print(np.dot(a,b))
print("====================")
print("dot product of a and b: ")
print(a.dot(b))
print("====================")
print("dot product of a and b: ")
print(a @ b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 90  91  92]
 [ 93  94  95]
 [ 96  97  98]
 [ 99 100 101]
 [102 103 104]]
dot product of a and b: 
[[ 990 1000 1010]
 [3390 3425 3460]
 [5790 5850 5910]]
dot product of a and b: 
[[ 990 1000 1010]
 [3390 3425 3460]
 [5790 5850 5910]]
dot product of a and b: 
[[ 990 1000 1010]
 [3390 3425 3460]
 [5790 5850 5910]]


---

## Finding `determinants`, `inverse` & `eigenvalues` of matrices

In [25]:
a = np.array([[7,-4,2],[3,1,-5],[2,2,-5]])
print(a)
print("===============================")

print("determinant of a: ", np.linalg.det(a))
print("===============================")

print("inverse of a: ", np.linalg.inv(a))
print("===============================")

print("eigenvalues of a: ", np.linalg.eigvals(a))


[[ 7 -4  2]
 [ 3  1 -5]
 [ 2  2 -5]]
determinant of a:  23.0
inverse of a:  [[ 0.2173913  -0.69565217  0.7826087 ]
 [ 0.2173913  -1.69565217  1.7826087 ]
 [ 0.17391304 -0.95652174  0.82608696]]
eigenvalues of a:  [ 6.08577221+0.j         -1.5428861 +1.18271265j -1.5428861 -1.18271265j]


---

## some numpy mathematical methods

```py
a = np.array([1, 2, 3])

print("square of array" ,np.square(a))
print("square root of array" ,np.sqrt(a))
print("log of array" ,np.log(a))
print("exp of array" ,np.exp(a))
```

In [26]:
a = np.array([1, 2, 3])

print("sum of array" ,np.sum(a))
print("max of array" ,np.max(a))
print("mean of array" ,np.mean(a))
print("median of array" ,np.median(a))
print("standard deviation of array" ,np.std(a))
print("variance of array" ,np.var(a))

print("-=====================--=====================--=====================-")

print("square of array" ,np.square(a))
print("square root of array" ,np.sqrt(a))
print("log of array" ,np.log(a))
print("exp of array" ,np.exp(a))


sum of array 6
max of array 3
mean of array 2.0
median of array 2.0
standard deviation of array 0.816496580927726
variance of array 0.6666666666666666
-=====================--=====================--=====================-
square of array [1 4 9]
square root of array [1.         1.41421356 1.73205081]
log of array [0.         0.69314718 1.09861229]
exp of array [ 2.71828183  7.3890561  20.08553692]


---

## Finding `mean-squared-error` using `numpy`


In [27]:
y_pred = np.arange(10)
y_true = np.arange(10) + np.random.rand(10) - 0.5

mean_squared_error = np.mean((y_pred - y_true)**2)
print(mean_squared_error)

0.09899832375101847


---

## How to `save` and `load` numpy data

- [visit here](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-save-and-load-numpy-objects) for more information

In [28]:
a = np.array([[1, 2, 3],[7,5,4]])

# save to file
np.save('my_array', a)

In [29]:
np.load('my_array.npy')

array([[1, 2, 3],
       [7, 5, 4]])